import {
  STANDARD_ARRAY_VALUES,
  UNASSIGNED_ABILITY_SCORES,
} from "@/features/character/create-character/lib/abilities/ability-pool";
import type { CreateCharacterInput } from "@/features/character/create-character/model/create-character.schema";

export const CREATE_CHARACTER_DEFAULT_VALUES: CreateCharacterInput = {
  name: "",
  level: 1,
  classSlug: "",
  speciesSlug: "",
  heritageSlug: "",
  backgroundSlug: "",
  characterThreadSlug: "",
  characterThreadGoalIndex: undefined,
  subclassSlug: "",
  abilityGenerationMethodSlug: "standard-array",
  abilityScores: { ...UNASSIGNED_ABILITY_SCORES },
  backgroundAbilityBoostMode: "plus2plus1",
  backgroundAbilityBoostPlus2Slug: "",
  backgroundAbilityBoostPlus1Slug: "",
  backgroundAbilityBoostPlus1Slugs: ["", "", ""],
  backgroundToolItemSlug: "",
  classSkillSlugs: [],
  abilityRawValues: [...STANDARD_ARRAY_VALUES],
  speciesChoices: [],
  heritageChoices: [],
  subclassOptions: [],
  classOptions: [],
  featOptions: [],
  asiFeatSlotSlugs: [],
  backgroundOriginFeatSlug: "",
  fightingStyleFeatSlug: "",
  alignmentSlug: "",
  languageSlugs: [],
  equipment: [],
  characterSpells: [],
};
